// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkQGxNbFcKNRdVmb-5xlukCkz5ZwMGFx0',
    appId: '1:427197985973:web:393db9f64ae174d3643afc',
    messagingSenderId: '427197985973',
    projectId: 'main-project-a90a4',
    authDomain: 'main-project-a90a4.firebaseapp.com',
    storageBucket: 'main-project-a90a4.firebasestorage.app',
    measurementId: 'G-3KG7YWL33T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQN-XgsY31cKESfSOECmxAfzNlnWEjQCg',
    appId: '1:427197985973:android:1032bcceca5fbd2c643afc',
    messagingSenderId: '427197985973',
    projectId: 'main-project-a90a4',
    storageBucket: 'main-project-a90a4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvh3liPcnwfUNXjrKtSRQCZ8IUFlSWWh8',
    appId: '1:427197985973:ios:1daf4cdbdeae2d3b643afc',
    messagingSenderId: '427197985973',
    projectId: 'main-project-a90a4',
    storageBucket: 'main-project-a90a4.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvh3liPcnwfUNXjrKtSRQCZ8IUFlSWWh8',
    appId: '1:427197985973:ios:1daf4cdbdeae2d3b643afc',
    messagingSenderId: '427197985973',
    projectId: 'main-project-a90a4',
    storageBucket: 'main-project-a90a4.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCkQGxNbFcKNRdVmb-5xlukCkz5ZwMGFx0',
    appId: '1:427197985973:web:30c9e7e04e5dd986643afc',
    messagingSenderId: '427197985973',
    projectId: 'main-project-a90a4',
    authDomain: 'main-project-a90a4.firebaseapp.com',
    storageBucket: 'main-project-a90a4.firebasestorage.app',
    measurementId: 'G-RX50BZVQPC',
  );
}
